nome = input('Olá! Qual é o seu nome? ')
print(f'Prazer em te conhecer, {nome}! ')
algo = input('Por gentileza, poderia digitar algo? Não importa o que seja, pode ter letras maiúsculas, minúsculas, números... ')
print(f'Qual é o tipo primitivo de {algo}? ', type(algo))
print(f'{algo} é composto apenas de números? ', algo.isnumeric())
print(f'{algo} é composto apenas de letras? ', algo.isalpha())
print(f'{algo} possui letras e números? ', algo.isalnum())
print(f'{algo} possui apenas letras minúsculas? ', algo.islower())
print(f'{algo} possui apenas letras maiúsculas? ', algo.isupper())
print(f'Prontinho! Respondi a você como {algo} é visto do ponto de vista técnico! ')